# ==============================================================================
# SYNTHETIC DEMONSTRATION DATA — NOT REAL GOVERNMENT RECORDS
# All identity credentials, names, document numbers, biometrics, and watchlist entries
# generated by this script are mathematically synthesized benchmark artifacts
# for local offline system evaluation and SIH demonstration purposes only.
# ==============================================================================

import os
import sys
import uuid
import random
import numpy as np
from datetime import datetime, timedelta, timezone

# Add backend directory to sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.core.database import SessionLocal, engine, Base
from app.db.models import (
    Checkpoint,
    Officer,
    DocumentType,
    ReferenceDocument,
    BlacklistedDocument,
    TravelerBiometric,
    ScreeningLog,
    ForensicReport
)
from app.core.audit_chain import compute_record_hash, GENESIS_HASH, verify_audit_chain
from app.services.validation.format_rules import compute_verhoeff_check_digit

FIRST_NAMES = [
    "Aarav", "Aditya", "Ajay", "Amit", "Anand", "Anil", "Ankit", "Arun", "Deepak", "Dinesh",
    "Gaurav", "Harish", "Karan", "Kavita", "Manoj", "Mohit", "Mukesh", "Neha", "Nitin", "Pankaj",
    "Pooja", "Pradeep", "Priya", "Rahul", "Rajesh", "Ravi", "Rohan", "Rohit", "Sachin", "Sandeep",
    "Sanjay", "Santosh", "Shashi", "Sunil", "Suresh", "Tarun", "Varun", "Vijay", "Vikas", "Vikram",
    "Vinay", "Vivek", "Ananya", "Divya", "Geeta", "Jyoti", "Meera", "Ritu", "Sneha", "Sunita"
]

LAST_NAMES = [
    "Sharma", "Verma", "Singh", "Kumar", "Gupta", "Yadav", "Pandey", "Mishra", "Patel", "Thakur",
    "Choudhary", "Bhatia", "Joshi", "Malik", "Mehta", "Chawla", "Prasad", "Dubey", "Tiwari", "Saxena",
    "Reddy", "Nair", "Iyer", "Banerjee", "Chatterjee", "Bose", "Dutta", "Das", "Sengupta", "Roy"
]

STATE_CODES = ["DL", "HR", "UP", "BR", "WB", "KA", "MH", "PB", "RJ", "MP", "UK", "AS"]
DOC_TYPES = ["PASSPORT", "AADHAAR", "DRIVING_LICENSE", "VOTER_ID"]

REASONS_BLACKLIST = [
    "MHA LOOKOUT CIRCULAR: Active lookout notice for transit interception.",
    "INTERPOL SLTD NOTICE: Stolen/lost travel document flagged in international registry.",
    "FRAUDULENT RING SUSPECT: Document associated with fabricated identity syndicate.",
    "REVOKED CREDENTIALS: Cancelled under Section 10(3) Passports Act.",
    "LOST DOCUMENT AFFIDAVIT: Passenger filed official lost identity declaration."
]

def generate_synthetic_passport(rng: random.Random) -> str:
    letter = rng.choice("ABCDEFGHJKLMNPQRSTUVWXYZ")
    digits = "".join(str(rng.randint(0, 9)) for _ in range(7))
    return f"{letter}{digits}"

def generate_synthetic_aadhaar(rng: random.Random, valid_checksum: bool = True) -> str:
    first_11 = "".join(str(rng.randint(1 if i == 0 else 0, 9)) for i in range(11))
    if valid_checksum:
        check_digit = compute_verhoeff_check_digit(first_11)
        return f"{first_11}{check_digit}"
    else:
        check_digit = int(compute_verhoeff_check_digit(first_11))
        bad_digit = (check_digit + rng.randint(1, 9)) % 10
        return f"{first_11}{bad_digit}"

def generate_synthetic_dl(rng: random.Random) -> str:
    st = rng.choice(STATE_CODES)
    rto = f"{rng.randint(1, 20):02d}"
    year = rng.randint(2010, 2024)
    seq = f"{rng.randint(1, 9999999):07d}"
    return f"{st}-{rto}{year}{seq}"

def generate_synthetic_voter_id(rng: random.Random) -> str:
    letters = "".join(rng.choice("ABCDEFGHJKLMNPQRSTUVWXYZ") for _ in range(3))
    digits = "".join(str(rng.randint(0, 9)) for _ in range(7))
    return f"{letters}{digits}"

def generate_synthetic_embedding(rng: random.Random, dim: int = 512) -> np.ndarray:
    vec = np.array([rng.gauss(0, 1) for _ in range(dim)], dtype=np.float32)
    norm = np.linalg.norm(vec)
    if norm > 0:
        vec /= norm
    return vec

def populate_and_redistribute():
    print("=== SIH26188 DATABASE NORMALIZATION & SYNTHETIC REDISTRIBUTION ===")
    rng = random.Random(1337)
    db = SessionLocal()

    try:
        # 1. Verify Checkpoints (All 23 must be present and active)
        checkpoints = db.query(Checkpoint).all()
        print(f"1. Checkpoints Loaded: {len(checkpoints)} active border checkpoints")
        if len(checkpoints) < 23:
            print(f"   Warning: expected at least 23 checkpoints, found {len(checkpoints)}")

        # 2. Add Synthetic VOTER_ID Reference Records
        print("\n2. Checking & Expanding VOTER_ID Reference Records...")
        existing_voters = db.query(ReferenceDocument).filter(ReferenceDocument.document_type == "VOTER_ID").count()
        print(f"   Current VOTER_ID reference records: {existing_voters}")

        if existing_voters < 300:
            voter_refs = []
            voter_blacks = []
            voter_bios = []

            for i in range(350):
                v_num = generate_synthetic_voter_id(rng)
                name = f"{rng.choice(FIRST_NAMES)} {rng.choice(LAST_NAMES)}".upper()
                dob = f"{rng.randint(1965, 2004)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}"
                issue = f"{rng.randint(2015, 2023)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}"
                expiry = f"{rng.randint(2028, 2038)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}"

                if i < 70:
                    status = "BLACKLISTED"
                    reason = rng.choice(REASONS_BLACKLIST)
                    source = "MHA_LOOKOUT"
                    voter_blacks.append(BlacklistedDocument(
                        document_type="VOTER_ID",
                        document_number=v_num,
                        holder_name=name,
                        reason=reason
                    ))
                elif i < 110:
                    status = "EXPIRED"
                    reason = "EXPIRED_DOCUMENT: Validity expired."
                    source = "SYNTHETIC_EXPIRED_SET"
                    expiry = f"{rng.randint(2018, 2023)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}"
                elif i < 130:
                    status = "SUSPICIOUS"
                    reason = "BORDER INTEL ALERT: High-frequency anomaly flagged."
                    source = "BORDER_INTEL"
                else:
                    status = "VALID"
                    reason = "VERIFIED_BENCHMARK: Valid voter identity enrolled."
                    source = "SYNTHETIC_VALID_SET"

                voter_refs.append(ReferenceDocument(
                    document_type="VOTER_ID",
                    document_number=v_num,
                    holder_name=name,
                    date_of_birth=dob,
                    issue_date=issue,
                    expiry_date=expiry,
                    status=status,
                    reason=reason,
                    source_type=source
                ))

                if status == "VALID":
                    emb = generate_synthetic_embedding(rng)
                    voter_bios.append(TravelerBiometric(
                        document_number=v_num,
                        holder_name=name,
                        face_embedding=emb.tobytes(),
                        embedding_engine="OpenCV-SpatialGradient-512D",
                        embedding_dimension=512,
                        status="ACTIVE"
                    ))

            db.add_all(voter_refs)
            db.add_all(voter_blacks)
            db.add_all(voter_bios)
            db.commit()
            print(f"   + Added {len(voter_refs)} synthetic VOTER_ID reference records ({len(voter_blacks)} blacklisted)")

        # 3. Redistribute Screening History across ALL 23 Checkpoints
        print("\n3. Redistributing Synthetic Screening Logs across ALL 23 Checkpoints...")
        
        # Clear existing screening logs & reports to build fresh, balanced, unbroken ledger
        db.query(ForensicReport).delete()
        db.query(ScreeningLog).delete()
        db.commit()

        officers = db.query(Officer).filter(Officer.status == "ACTIVE").all()
        officers_by_cp = {}
        for off in officers:
            if off.checkpoint_id:
                officers_by_cp.setdefault(off.checkpoint_id, []).append(off)

        # Fallback officer list
        default_officers = officers if officers else [
            Officer(badge_id="SSB-7741", full_name="Inspector R. K. Sharma", role="OFFICER")
        ]

        now = datetime.now(timezone.utc)
        generated_logs_data = []

        # Target: 10 to 16 screenings per checkpoint (Total ~260-300 records)
        for cp in checkpoints:
            cp_officers = officers_by_cp.get(cp.id, default_officers)
            num_screenings = rng.randint(10, 15)

            for s_idx in range(num_screenings):
                # Spread timestamps over past 28 days
                days_ago = rng.uniform(0.05, 28.0)
                t_stamp = now - timedelta(days=days_ago)

                off = rng.choice(cp_officers)
                doc_type = rng.choice(DOC_TYPES)
                name = f"{rng.choice(FIRST_NAMES)} {rng.choice(LAST_NAMES)}".upper()

                if doc_type == "PASSPORT":
                    doc_num = generate_synthetic_passport(rng)
                elif doc_type == "AADHAAR":
                    doc_num = generate_synthetic_aadhaar(rng, valid_checksum=True)
                elif doc_type == "DRIVING_LICENSE":
                    doc_num = generate_synthetic_dl(rng)
                else:
                    doc_num = generate_synthetic_voter_id(rng)

                # Determine Risk Distribution: ~60% LOW, ~15% MEDIUM, ~25% HIGH
                dice = rng.random()
                if dice < 0.60:
                    risk_level = "LOW"
                    overall_risk = round(rng.uniform(12.0, 34.0), 1)
                    tamper_score = round(rng.uniform(4.0, 18.0), 1)
                    face_score = round(rng.uniform(78.0, 96.0), 1)
                    flags = []
                    decision = "APPROVED" if days_ago > 0.5 else ("PENDING" if rng.random() < 0.4 else "APPROVED")
                    notes = "All biometric and document checks verified clear at terminal." if decision == "APPROVED" else ""
                elif dice < 0.75:
                    risk_level = "MEDIUM"
                    overall_risk = round(rng.uniform(42.0, 62.0), 1)
                    tamper_score = round(rng.uniform(25.0, 48.0), 1)
                    face_score = round(rng.uniform(55.0, 72.0), 1)
                    flags = [{
                        "code": "SUSPICIOUS_BORDER_ANOMALY",
                        "title": "Minor Signal Anomaly",
                        "message": "Mild compression variance detected on document boundary.",
                        "severity": "MEDIUM",
                        "source": "Forensics"
                    }]
                    decision = "ESCALATED" if days_ago > 0.5 else ("PENDING" if rng.random() < 0.5 else "ESCALATED")
                    notes = "Escalated for secondary physical document verification." if decision == "ESCALATED" else ""
                else:
                    risk_level = "HIGH"
                    overall_risk = round(rng.uniform(72.0, 96.0), 1)
                    tamper_score = round(rng.uniform(65.0, 92.0), 1)
                    face_score = round(rng.uniform(22.0, 46.0), 1)
                    flags = [{
                        "code": "FORENSIC_TAMPERING_DETECTED",
                        "title": "High Tampering Probability",
                        "message": "Multi-signal ELA and DCT grid analysis indicates synthetic digital alteration.",
                        "severity": "CRITICAL",
                        "source": "Forensics"
                    }]
                    decision = "REJECTED" if days_ago > 0.5 else ("PENDING" if rng.random() < 0.3 else "REJECTED")
                    notes = "Denied transit due to flagged forensic alterations." if decision == "REJECTED" else ""

                extracted_data = {
                    "document_type": doc_type,
                    "document_number": doc_num,
                    "holder_name": name,
                    "dob": f"{rng.randint(1970, 2002)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}",
                    "gender": rng.choice(["MALE", "FEMALE"]),
                    "nationality": "INDIAN"
                }

                proc_time = round(rng.uniform(450.0, 850.0), 1)
                ocr_time = round(proc_time * rng.uniform(0.35, 0.45), 1)
                forensics_time = round(proc_time * rng.uniform(0.25, 0.35), 1)
                biometric_time = round(proc_time - ocr_time - forensics_time, 1)

                log_id = str(uuid.uuid4())

                generated_logs_data.append({
                    "id": log_id,
                    "timestamp": t_stamp,
                    "checkpoint_id": cp.id,
                    "checkpoint_location": cp.name,
                    "officer_id": off.badge_id,
                    "document_type": doc_type,
                    "document_number": doc_num,
                    "holder_name": name,
                    "raw_document_image_path": f"/static/uploads/{log_id}_doc.jpg",
                    "raw_live_photo_path": f"/static/uploads/{log_id}_live.jpg",
                    "tamper_heatmap_path": f"/static/heatmaps/{log_id}_heatmap.png" if tamper_score > 30 else None,
                    "extracted_data_json": extracted_data,
                    "validation_flags_json": flags,
                    "tampering_score": tamper_score,
                    "face_match_score": face_score,
                    "overall_risk_score": overall_risk,
                    "risk_level": risk_level,
                    "officer_decision": decision,
                    "officer_notes": notes,
                    "processing_time_ms": proc_time,
                    "ocr_time_ms": ocr_time,
                    "forensics_time_ms": forensics_time,
                    "biometric_time_ms": biometric_time,
                    "pipeline_version": "2.0.0",
                    # Forensic report info
                    "ela_score": round(tamper_score * rng.uniform(0.8, 1.1), 1),
                    "jpeg_score": round(tamper_score * rng.uniform(0.7, 1.2), 1),
                    "boundary_score": round(tamper_score * rng.uniform(0.75, 1.15), 1),
                    "exif_score": round(rng.uniform(0.0, 20.0), 1)
                })

        # Sort all logs strictly ascending by timestamp for flawless SHA-256 block chaining
        generated_logs_data.sort(key=lambda x: x["timestamp"])

        # Compute continuous SHA-256 audit hashes
        screening_entities = []
        forensic_entities = []
        prev_hash = GENESIS_HASH

        for item in generated_logs_data:
            rec_hash = compute_record_hash(
                record_id=item["id"],
                timestamp_str=str(item["timestamp"]),
                checkpoint_location=item["checkpoint_location"],
                officer_id=item["officer_id"],
                document_type=item["document_type"],
                document_number=item["document_number"],
                overall_risk_score=item["overall_risk_score"],
                risk_level=item["risk_level"],
                officer_decision=item["officer_decision"],
                prev_log_hash=prev_hash
            )

            log_obj = ScreeningLog(
                id=item["id"],
                timestamp=item["timestamp"],
                checkpoint_id=item["checkpoint_id"],
                checkpoint_location=item["checkpoint_location"],
                officer_id=item["officer_id"],
                document_type=item["document_type"],
                document_number=item["document_number"],
                holder_name=item["holder_name"],
                raw_document_image_path=item["raw_document_image_path"],
                raw_live_photo_path=item["raw_live_photo_path"],
                tamper_heatmap_path=item["tamper_heatmap_path"],
                extracted_data_json=item["extracted_data_json"],
                validation_flags_json=item["validation_flags_json"],
                tampering_score=item["tampering_score"],
                face_match_score=item["face_match_score"],
                overall_risk_score=item["overall_risk_score"],
                risk_level=item["risk_level"],
                officer_decision=item["officer_decision"],
                officer_notes=item["officer_notes"],
                prev_log_hash=prev_hash,
                record_hash=rec_hash,
                processing_time_ms=item["processing_time_ms"],
                ocr_time_ms=item["ocr_time_ms"],
                forensics_time_ms=item["forensics_time_ms"],
                biometric_time_ms=item["biometric_time_ms"],
                pipeline_version=item["pipeline_version"]
            )
            screening_entities.append(log_obj)

            forensic_rep = ForensicReport(
                id=str(uuid.uuid4()),
                screening_id=item["id"],
                ela_score=item["ela_score"],
                exif_score=item["exif_score"],
                boundary_score=item["boundary_score"],
                jpeg_score=item["jpeg_score"],
                overall_tampering_score=item["tampering_score"],
                heatmap_path=item["tamper_heatmap_path"],
                pipeline_version="2.0.0",
                engine_metadata_json={
                    "ela_algorithm": "ELA-90% JPEG Recompression Baseline",
                    "jpeg_algorithm": "8x8 Block DCT Quantization Grid Analyzer",
                    "boundary_algorithm": "Canny Gradient Edge Discontinuity",
                    "exif_status": ["CLEAN_CAMERA_SIGNATURE"] if item["exif_score"] < 10 else ["MISSING_METADATA"]
                }
            )
            forensic_entities.append(forensic_rep)

            prev_hash = rec_hash

        db.add_all(screening_entities)
        db.add_all(forensic_entities)
        db.commit()

        print(f"   + Successfully written {len(screening_entities)} distributed screening logs across {len(checkpoints)} checkpoints.")

        # 4. Run Integrity Check
        print("\n4. Checking Database Integrity...")
        conn = db.connection()
        fk_errors = list(conn.execute(engine.raw_connection().cursor().execute if False else Base.metadata.tables["screening_logs"].select().limit(0)))
        
        # Check SQLite PRAGMA
        cursor = db.connection().connection.cursor()
        cursor.execute("PRAGMA foreign_key_check;")
        fk_violations = cursor.fetchall()
        print(f"   Foreign Key Check: {len(fk_violations)} violations found (0 expected).")

        # 5. Verify SHA-256 Audit Chain
        print("\n5. Verifying SHA-256 Audit Chain...")
        all_logs = db.query(ScreeningLog).order_by(ScreeningLog.timestamp.asc()).all()
        is_valid, msg, total_checked, inv_id = verify_audit_chain(all_logs)
        print(f"   Audit Chain Valid: {is_valid}")
        print(f"   Total Records Checked: {total_checked}")
        print(f"   First Invalid Record: {inv_id}")
        print(f"   Last Record Hash: {all_logs[-1].record_hash if all_logs else None}")
        print(f"   Message: {msg}")

    finally:
        db.close()

if __name__ == "__main__":
    populate_and_redistribute()
