"""initial_schema_v2

Revision ID: f931763fb82f
Revises: 
Create Date: 2026-09-01 13:12:33.977997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f931763fb82f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.alter_column('checkpoint_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
        batch_op.create_foreign_key(None, 'checkpoints', ['checkpoint_id'], ['id'])

    with op.batch_alter_table('screening_logs', schema=None) as batch_op:
        batch_op.alter_column('pipeline_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'2.0.0'"))
        batch_op.create_foreign_key(None, 'checkpoints', ['checkpoint_id'], ['id'])

    with op.batch_alter_table('traveler_biometrics', schema=None) as batch_op:
        batch_op.alter_column('embedding_engine',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'OpenCV-SpatialGradient-512D'"))
        batch_op.alter_column('embedding_dimension',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(512)'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traveler_biometrics', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'"))
        batch_op.alter_column('embedding_dimension',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(512)'))
        batch_op.alter_column('embedding_engine',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'OpenCV-SpatialGradient-512D'"))

    with op.batch_alter_table('screening_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('pipeline_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'2.0.0'"))

    with op.batch_alter_table('officers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'"))
        batch_op.alter_column('checkpoint_location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
